// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PuzzleType } from "./PuzzleType";
import type { WordSearchData } from "./WordSearchData";

export type PuzzlePayload = {
  id: string;
  puzzle_type: PuzzleType;
  title: string;
  grid: Array<Array<string>>;
  specific_data: WordSearchData;
};
