// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WordPlacement } from "./WordPlacement";

export type WordSearchData = {
  word_bank: Array<string>;
  unplaced_words: Array<string>;
  solutions: Array<WordPlacement>;
};
